In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv
from collections import Counter, defaultdict
import sklearn as sk

#### Get and clean the data

In [2]:
df = pd.read_csv("house-votes-84.csv")#, skiprows = 1, header = None)

In [3]:
df.head(10)

,Class Name,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,republican,n,y,n,y,y,y,n,n,n,y,?,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,?
2,democrat,?,y,y,?,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,?,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,?,y,y,y,y
5,democrat,n,y,y,n,y,y,n,n,n,n,n,n,y,y,y,y
6,democrat,n,y,n,y,y,y,n,n,n,n,n,n,?,y,y,y
7,republican,n,y,n,y,y,y,n,n,n,n,n,n,y,y,?,y
8,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
9,democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,?,?

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df.isna().sum()

Class Name                                 0
 handicapped-infants                       0
 water-project-cost-sharing                0
 adoption-of-the-budget-resolution         0
 physician-fee-freeze                      0
 el-salvador-aid                           0
 religious-groups-in-schools               0
 anti-satellite-test-ban                   0
 aid-to-nicaraguan-contras                 0
 mx-missile                                0
 immigration                               0
 synfuels-corporation-cutback              0
 education-spending                        0
 superfund-right-to-sue                    0
 crime                                     0
 duty-free-exports                         0
 export-administration-act-south-africa    0
dtype: int64

In [6]:
df.replace("?", np.nan, inplace = True)

In [7]:
df = df[df.notna().all(axis=1)]
df

,Class Name,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
5,democrat,n,y,y,n,y,y,n,n,n,n,n,n,y,y,y,y
8,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
19,democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y
23,democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,y
25,democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,democrat,n,y,y,n,n,y,y,y,y,n,y,n,n,y,y,y
426,democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y
427,republican,n,n,n,y,y,y,y,y,n,y,n,y,y,y,n,y
430,republican,n,n,y,y,y,y,n,n,y,y,n,y,y,y,n,y
431,democrat,n,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y

In [8]:
# Reset as RangeIndex(start=0, stop=9, step=1)

df.reset_index(inplace=True)
df.index

RangeIndex(start=0, stop=232, step=1)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 18 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   index                                    232 non-null    int64
 1   Class Name                               232 non-null    object
 2    handicapped-infants                     232 non-null    object
 3    water-project-cost-sharing              232 non-null    object
 4    adoption-of-the-budget-resolution       232 non-null    object
 5    physician-fee-freeze                    232 non-null    object
 6    el-salvador-aid                         232 non-null    object
 7    religious-groups-in-schools             232 non-null    object
 8    anti-satellite-test-ban                 232 non-null    object
 9    aid-to-nicaraguan-contras               232 non-null    object
 10   mx-missile                              232 non-null    object
 11   immigration                             232 non-null    object
 12   synfuels-corporation-cutback            232 non-null    object
 13   education-spending                      232 non-null    object
 14   superfund-right-to-sue                  232 non-null    object
 15   crime                                   232 non-null    object
 16   duty-free-exports                       232 non-null    object
 17   export-administration-act-south-africa  232 non-null    object
dtypes: int64(1), object(17)
memory usage: 32.8+ KB

In [10]:
X = df.drop(["Class Name", "index"], axis = 1)
X.head(3)

,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,n,y,y,n,y,y,n,n,n,n,n,n,y,y,y,y
1,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
2,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y

In [11]:
features = list(X.columns)
features

[' handicapped-infants',
 ' water-project-cost-sharing',
 ' adoption-of-the-budget-resolution',
 ' physician-fee-freeze',
 ' el-salvador-aid',
 ' religious-groups-in-schools',
 ' anti-satellite-test-ban',
 ' aid-to-nicaraguan-contras',
 ' mx-missile',
 ' immigration',
 ' synfuels-corporation-cutback',
 ' education-spending',
 ' superfund-right-to-sue',
 ' crime',
 ' duty-free-exports',
 ' export-administration-act-south-africa']

In [12]:
y = df["Class Name"]
y.value_counts()

democrat      124
republican    108
Name: Class Name, dtype: int64

Will this work better with numbers instead of column names?  I
changed the X dataframe columns to numbers.  It still doesn't work and I really don't like working with column numbers so I changed
it back.

In [13]:
#X.values

In [14]:
#X = pd.DataFrame.from_records(X.values)

In [15]:
X.head()

,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,n,y,y,n,y,y,n,n,n,n,n,n,y,y,y,y
1,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
2,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y
3,y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,y
4,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y

#### Divide the data into training and testing data

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 110)

In [18]:
X_train.head(3)

,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
142,n,n,y,y,y,y,y,y,n,y,n,n,n,y,n,y
140,y,n,n,y,y,n,y,n,n,y,n,n,n,y,y,y
103,n,n,n,y,y,y,n,n,n,y,n,y,n,y,n,y

#### Get the unique value counts for all the columns.
This is not much of a problem for one column, but for the 
whole dataset it doesn't seem to work

In [19]:
X_train[" handicapped-infants"].value_counts()

n    107
y     78
Name:  handicapped-infants, dtype: int64

In [20]:
def unique_values(rows, col):
    #maybe use for index, row in data.iterrows()?:
    return set([row[col] for row in rows])

In [21]:
#unique_values(X_train, 1)  Gives error "'int' object is not subscriptable"

Down to here is my own code and I understand it.  Below are modified versions of code I found on the
internet to accomplish the tasks I have indicated in bold.  Nothing works except is_numeric.

#### Count the number of each type of value for each y label in each column
This should show the counts of x and y connected to Republican or Democrat

In [22]:
def sample_counts(rows):
    '''Counts the number of each type of example in a dataset'''
    counts = {}
    for row in rows:
        label = y.index
        if y.index == X.index:
            continue
        if label not in counts:
            counts[label] = 0
        counts[label] += 1
    return counts

In [23]:
#sample_counts(X_train)

In [24]:
def is_numeric(value):
    return isinstance(value, int) or isinstance(value, float)

In [25]:
is_numeric(7)

True

#### Ask a question which feature is going to give the maximum info gain and minimum GINI.

In [26]:
class Ask:

    def __init__(self, column, value):
        self.column = column
        self.value = value
        
    def match(self, sample):
        value_s = sample[self.column]
        if is_numeric(value_s):
            return value_s >= self.value
        else:
            return value_s == self.value
    
    #Representation - only needed if some of the values are numeric. Format gets the values in the columns
    def __repr__(self):
        return Ask("Is {self.column} greater than {self.value}?")

In [27]:
ask = Ask(1,2)

#### Create function to partition the rows into y and n

In [28]:
sample = X_train[0]

KeyError: 0

In [ ]:
ask.match(sample)

In [29]:
def partition(rows, ask):
    
    yes_rows, no_rows = [], []
    for row in rows:
        if ask.match(row):
            yes_rows.append(row)
        else:
            yes_rows.append(row)
    return yes_rows, no_rows

In [30]:
yes_rows, no_rows = partition(X_train, Ask(0, "democrat"))
#yes_rows

In [31]:
no_rows

[]

#### Apply GINI to the counts

In [32]:
def gini(rows):
    counts = class_counts(rows)
    impurity = 1
    for lbl in counts:
        t = len(self.X)
        p = df.groupby(self.y).size()/t
        impurity = 1- sum(p **2)
    return impurity

#### Get the information gain

In [33]:
def info_gain(left, right, current_uncertainty):
    p = float(len(left)) / (len(left) + len(right))
    return current_uncertainty - p * gini(left) - (1-p) * gini(right)

#### Calculate current uncertainty

In [34]:
uncertainty = gini(X_train)
uncertainty

NameError: name 'class_counts' is not defined

In [37]:
true_rows, false_rows = partition(X_train, Ask(0, 1))
info_gain(true_rows, false_rows, uncertainty)

NameError: name 'uncertainty' is not defined

#### Find best split

In [ ]:
def find_best_split(rows):
    best_gain = 0
    best_ask = None
    uncertainty - gini(rows)
    num_features = len(rows[0]) -1
    
    for col in range(num_features): 
        
        values = set([row[col] for row in rows])  #unique values in the column
        
        for val in values: #for each vale
            ask = Ask(col, val)
            
            true_rows, false_rows = partition(rows, ask)
            
            if len(true_rows) == 0 or len(false_rows) == 0:
                continue
                
            gain = info_gain(true_rows, false_rows, uncertainty)
            
            if gain >= best_gain:
                best_gain, best_ask = gain, ask
                
        return best_gain, best_ask

In [ ]:
best_gain, best_ask = find_best_split(X_train)
best_ask

In [ ]:
best_gain

#### Create a class for the Leaf node and Decision Node

In [ ]:
class Leaf:
    def __init__(self, rows):
        self.predictions = class_counts(rows)

In [ ]:
class DecisionNode:
    def __init__(self, ask, true_branch, false_branch):
        self.ask = ask
        self.true_branch = true_branch
        self.false_branch = false_branch

####  Build tree with function

In [ ]:
def build_tree(rows):
    gain, ask = find_best_split(rows) #pass entire data set
    if gain == 0:
        return Leaf(rows)
    
    true_rows, false_rows = partition(rows, ask)
    true_branch = build_tree(true_rows)
    false_branch = build_tree(false_rows)
    return DecisionNode(ask, true_branch, false_branch)

#### Make the predictions

In [ ]:
def predict(rows):